// Code generated by MockGen. DO NOT EDIT.
// Source: ../websocket.go
//
// Generated by this command:
//
//	mockgen -source=../websocket.go -destination=./mock.go
//

// Package mock_planningpoker is a generated GoMock package.
package mock_planningpoker

import (
	reflect "reflect"

	planningpoker "github.com/canpok1/web-toolbox/backend/internal/api/planningpoker"
	echo "github.com/labstack/echo/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockWebSocketHubInterface is a mock of WebSocketHubInterface interface.
type MockWebSocketHubInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWebSocketHubInterfaceMockRecorder
	isgomock struct{}
}

// MockWebSocketHubInterfaceMockRecorder is the mock recorder for MockWebSocketHubInterface.
type MockWebSocketHubInterfaceMockRecorder struct {
	mock *MockWebSocketHubInterface
}

// NewMockWebSocketHubInterface creates a new mock instance.
func NewMockWebSocketHubInterface(ctrl *gomock.Controller) *MockWebSocketHubInterface {
	mock := &MockWebSocketHubInterface{ctrl: ctrl}
	mock.recorder = &MockWebSocketHubInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebSocketHubInterface) EXPECT() *MockWebSocketHubInterfaceMockRecorder {
	return m.recorder
}

// BroadcastParticipantJoined mocks base method.
func (m *MockWebSocketHubInterface) BroadcastParticipantJoined(participantId, name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastParticipantJoined", participantId, name)
}

// BroadcastParticipantJoined indicates an expected call of BroadcastParticipantJoined.
func (mr *MockWebSocketHubInterfaceMockRecorder) BroadcastParticipantJoined(participantId, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastParticipantJoined", reflect.TypeOf((*MockWebSocketHubInterface)(nil).BroadcastParticipantJoined), participantId, name)
}

// BroadcastRoundStarted mocks base method.
func (m *MockWebSocketHubInterface) BroadcastRoundStarted(roundId string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastRoundStarted", roundId)
}

// BroadcastRoundStarted indicates an expected call of BroadcastRoundStarted.
func (mr *MockWebSocketHubInterfaceMockRecorder) BroadcastRoundStarted(roundId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastRoundStarted", reflect.TypeOf((*MockWebSocketHubInterface)(nil).BroadcastRoundStarted), roundId)
}

// BroadcastSessionEnded mocks base method.
func (m *MockWebSocketHubInterface) BroadcastSessionEnded() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastSessionEnded")
}

// BroadcastSessionEnded indicates an expected call of BroadcastSessionEnded.
func (mr *MockWebSocketHubInterfaceMockRecorder) BroadcastSessionEnded() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastSessionEnded", reflect.TypeOf((*MockWebSocketHubInterface)(nil).BroadcastSessionEnded))
}

// BroadcastVoteSubmitted mocks base method.
func (m *MockWebSocketHubInterface) BroadcastVoteSubmitted(participantId string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastVoteSubmitted", participantId)
}

// BroadcastVoteSubmitted indicates an expected call of BroadcastVoteSubmitted.
func (mr *MockWebSocketHubInterfaceMockRecorder) BroadcastVoteSubmitted(participantId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastVoteSubmitted", reflect.TypeOf((*MockWebSocketHubInterface)(nil).BroadcastVoteSubmitted), participantId)
}

// BroadcastVotesRevealed mocks base method.
func (m *MockWebSocketHubInterface) BroadcastVotesRevealed(votes []planningpoker.Vote, average, median float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastVotesRevealed", votes, average, median)
}

// BroadcastVotesRevealed indicates an expected call of BroadcastVotesRevealed.
func (mr *MockWebSocketHubInterfaceMockRecorder) BroadcastVotesRevealed(votes, average, median any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastVotesRevealed", reflect.TypeOf((*MockWebSocketHubInterface)(nil).BroadcastVotesRevealed), votes, average, median)
}

// HandleWebSocket mocks base method.
func (m *MockWebSocketHubInterface) HandleWebSocket(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleWebSocket", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleWebSocket indicates an expected call of HandleWebSocket.
func (mr *MockWebSocketHubInterfaceMockRecorder) HandleWebSocket(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleWebSocket", reflect.TypeOf((*MockWebSocketHubInterface)(nil).HandleWebSocket), c)
}

// Run mocks base method.
func (m *MockWebSocketHubInterface) Run() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run")
}

// Run indicates an expected call of Run.
func (mr *MockWebSocketHubInterfaceMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockWebSocketHubInterface)(nil).Run))
}
