.PHONY: setup
setup:
	npm ci

.PHONY: run
run:
	npm run dev

.PHONY: check
check:
	npm run check

.PHONY: format
format:
	npm run check:fix

.PHONY: test
test:
	npm run test

.PHONY: build
build:
	npm run build
