openapi: 3.0.0
info:
  title: Planning Poker API
  version: v1
paths:
  /api/planning-poker/sessions:
    post:
      summary: セッションを作成する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSessionRequest"
      responses:
        "201":
          description: セッション作成成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateSessionResponse"
        "400":
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/planning-poker/sessions/{sessionId}/participants:
    post:
      summary: セッションに参加する
      parameters:
        - in: path
          name: sessionId
          schema:
            type: string
            format: uuid
          required: true
          description: セッションID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JoinSessionRequest"
      responses:
        "201":
          description: セッション参加成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JoinSessionResponse"
        "400":
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: セッションが見つからない
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/planning-poker/sessions/{sessionId}:
    get:
      summary: セッションを取得する
      parameters:
        - in: path
          name: sessionId
          schema:
            type: string
            format: uuid
          required: true
          description: セッションID
      responses:
        "200":
          description: セッション取得成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetSessionResponse"
        "404":
          description: セッションが見つからない
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/planning-poker/sessions/{sessionId}/end:
    post:
      summary: セッションを終了する
      parameters:
        - in: path
          name: sessionId
          schema:
            type: string
            format: uuid
          required: true
          description: セッションID
      responses:
        "200":
          description: セッション終了成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EndSessionResponse"
        "404":
          description: セッションが見つからない
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/planning-poker/sessions/{sessionId}/rounds:
    post:
      summary: ラウンドを開始する
      parameters:
        - in: path
          name: sessionId
          schema:
            type: string
            format: uuid
          required: true
          description: セッションID
      responses:
        "201":
          description: ラウンド開始成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StartRoundResponse"
        "400":
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: セッションが見つからない
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/planning-poker/rounds/{roundId}/reveal:
    post:
      summary: ラウンドを終了する
      parameters:
        - in: path
          name: roundId
          schema:
            type: string
            format: uuid
          required: true
          description: ラウンドID
      responses:
        "200":
          description: ラウンド終了成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RevealRoundResponse"
        "404":
          description: ラウンドが見つからない
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/planning-poker/rounds/{roundId}/votes:
    post:
      summary: 投票を送信する
      parameters:
        - in: path
          name: roundId
          schema:
            type: string
            format: uuid
          required: true
          description: ラウンドID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendVoteRequest"
      responses:
        "201":
          description: 投票送信成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SendVoteResponse"
        "400":
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: ラウンドが見つからない
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    ScaleType:
      type: string
      enum:
        - fibonacci
        - t-shirt
        - custom
    CreateSessionRequest:
      type: object
      required:
        - sessionName
        - scaleType
        - hostName
      properties:
        sessionName:
          type: string
        scaleType:
          $ref: "#/components/schemas/ScaleType"
        customScale:
          type: array
          items:
            type: string
        hostName:
          type: string
    CreateSessionResponse:
      type: object
      required:
        - sessionId
        - hostId
      properties:
        sessionId:
          type: string
          format: uuid
        hostId:
          type: string
          format: uuid
    JoinSessionRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    JoinSessionResponse:
      type: object
      required:
        - participantId
      properties:
        participantId:
          type: string
          format: uuid
    GetSessionResponse:
      type: object
      required:
        - sessionId
        - sessionName
        - hostId
        - scaleType
        - customScale
        - status
        - createdAt
        - updatedAt
      properties:
        sessionId:
          type: string
          format: uuid
        sessionName:
          type: string
        hostId:
          type: string
          format: uuid
        scaleType:
          $ref: "#/components/schemas/ScaleType"
        customScale:
          type: array
          items:
            type: string
        currentRoundId:
          type: string
          format: uuid
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    EndSessionResponse:
      type: object
    StartRoundResponse:
      type: object
      required:
        - roundId
      properties:
        roundId:
          type: string
          format: uuid
    RevealRoundResponse:
      type: object
    SendVoteRequest:
      type: object
      required:
        - participantId
        - value
      properties:
        participantId:
          type: string
          format: uuid
        value:
          type: string
    SendVoteResponse:
      type: object
      required:
        - voteId
      properties:
        voteId:
          type: string
          format: uuid
