.PHONY: setup
setup:
	npm ci
	npm run setup

.PHONY: test
test:
	npm test

.PHONY: test-debug
test-debug:
	npm run test:debug

.PHONY: show-report
show-report:
	npm run show-report

.PHONY: check
check:
	npm run check

.PHONY: format
format:
	npm run check:fix
