name: build

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: "backend/go.mod"
          cache-dependency-path: "backend/go.sum"

      - uses: actions/setup-node@v4
        with:
          node-version-file: "frontend/package.json"

      - name: Setup
        run: make setup

      - name: Code generate check
        run: |
          make generate
          git diff --ignore-space-change --exit-code

      - name: Run test
        run: |
          make test

  build:
    runs-on: ubuntu-latest
    needs: [check]

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}/server:latest

  test-e2e:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright
    needs: [check]

    services:
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: "backend/go.mod"
          cache-dependency-path: "backend/go.sum"

      - uses: actions/setup-node@v4
        with:
          node-version-file: "frontend/package.json"

      - name: Setup
        run: |
          make setup
          make setup-e2e

      - name: Build-front
        run: make build-front

      - name: Run e2e test
        run: |
          make test-e2e

  deploy-web:
    runs-on: ubuntu-latest
    needs: [build, test-e2e]
    environment: production-web
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to web server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ vars.DEPLOY_DIR }}
            git checkout main
            git pull origin main
            docker-compose pull
            docker-compose up -d
            docker system prune -f
